### ISSUE TITLE
[FEATURE REQUEST]: Hide club select based on club count instead of fetcher type

### ISSUE THREAD

**Issue by martijnvankekem** [Martijn-van-Kekem-Development/hockey-match-calendar#91]
### Explain your feature.

Currently, the club select is hidden for the 'EH' fetcher.
Change this to hide it when there are no clubs to filter for.

### Added value.

Better code maintainability.

**Comment by philipohagan** [comment]
Just fyi - the reason I hid it was because the underlying data was really messy and the clubs that were 'created' didn't make sense vs there being none.
